### ISSUE TITLE
Webhooks: mistake in examples of configurations

### ISSUE THREAD

**Issue by CasaMare** [buggregator/docs#35]
1)There is a mistake in path where should be yaml files with webhooks configuration.

In documentation :
/path/to/webhooks:/app/runtime/webhooks

Should be : 
/path/to/webhooks:/app/runtime/configs

2)It's neccessary to add example of naming of webhook configuration file because server try to find files by this pattern *.webhook.yaml

**Comment by butschster** [comment]
@CasaMare Thx!
